
# 配置hystrix的参数
hystrix:
  threadpool:
    # default: 默认参数，作用的所有的hystrix的客户端
    default:
      coreSize: 10
  command:
    default:
      fallback:
        # 是否开启回退方法
        enabled: true
# feign配置
feign:
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: true